GITHUB_TOKEN = "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"
GITHUB_REPO = "https://github.com/Aravind224400/contractor-salary-data.git"
GITHUB_BRANCH = "main"
ADMIN_PASSWORD = "dada"
VIEW_PASSWORD = "work"
