# .streamlit/secrets.toml

# 1. The URL of your Supabase project (from the traceback: SUPABASE_URL)
# Replace the placeholder value with your actual URL.
SUPABASE_URL = "https://hjzovjivayxzklktnvdo.supabase.co"

# 2. The Service Role Key (or equivalent API key) for Supabase
# This is often needed for backend access.
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhqem92aml2YXl4emtsa3RudmRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzNjg1NzgsImV4cCI6MjA3Njk0NDU3OH0.Z5ijigP0t5AagKmCAfwC1kOCcnPdfEQCoz28QfNrcGU"

# 3. Any other secrets your app might need, which could be causing the KeyError
# Example: If your app uses a database connection configuration block
admin_password = "dada"
viewer_password = "work"
[database]
user = "Aravind224400"
password = "Dada143@"
